# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.box_check_update = false
  #config.vm.network "forwarded_port", guest: 8081, host: 8080

  # config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.network "public_network", ip: "192.168.0.101"

  # config.vm.synced_folder "../data", "/vagrant_data"
  
  config.vm.hostname = "jenkins"
  
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  
     # Customize the amount of memory on the VM:
     vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install salt-minion salt-common ssh -y
      
      if ! grep -q "192.168.0.100" /etc/hosts; then
         echo "192.168.0.100   salt-master.anselmopfeifer.com salt-master"  >> /etc/hosts
         cat /etc/hosts
      fi

    SHELL

end
